import LandingPage from "./LandingPage"
import LoginPage from "./LoginPage"
import RegisterPage from "./RegisterPage"
import GeneratePage from "./GeneratePage"
import VerifyPage from "./VerifyPage"
import EmailSentPage from "./EmailSentPage"
import MyPallete from "./MyPalletePage"
import ForgetPassword from "./ForgetPassword"
import ForgetUsername from "./ForgetUsername"
import VerifyForgetPasswordPage from "./VerifyForgetPasswordPage"
import PublicPalletePage from "./PublicPalletePage"
import ImagePage from "./ImagePage"
import AiPage from "./AiPage"

export {AiPage, ImagePage, PublicPalletePage ,VerifyForgetPasswordPage, ForgetPassword ,ForgetUsername, MyPallete, EmailSentPage, VerifyPage, LandingPage, LoginPage, RegisterPage, GeneratePage}